[2025-06-19T11:21:06.785+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.evaluate_model_task manual__2025-06-19T11:15:39.535668+00:00 [queued]>
[2025-06-19T11:21:06.793+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.evaluate_model_task manual__2025-06-19T11:15:39.535668+00:00 [queued]>
[2025-06-19T11:21:06.793+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-06-19T11:21:06.827+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): evaluate_model_task> on 2025-06-19 11:15:39.535668+00:00
[2025-06-19T11:21:06.834+0000] {standard_task_runner.py:60} INFO - Started process 1020 to run task
[2025-06-19T11:21:06.838+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'evaluate_model_task', 'manual__2025-06-19T11:15:39.535668+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp7kh0tn2m']
[2025-06-19T11:21:06.840+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask evaluate_model_task
[2025-06-19T11:21:06.872+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T11:21:06.897+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.evaluate_model_task manual__2025-06-19T11:15:39.535668+00:00 [running]> on host 0064cba90111
[2025-06-19T11:21:07.003+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='evaluate_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T11:15:39.535668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T11:15:39.535668+00:00'
[2025-06-19T11:21:07.005+0000] {logging_mixin.py:188} INFO - Starting model evaluation task...
[2025-06-19T11:21:07.024+0000] {logging_mixin.py:188} INFO - Retrieved DataFrame with shape (200, 21) from key 'lung_cancer:model_features:test'
[2025-06-19T11:21:07.065+0000] {logging_mixin.py:188} INFO - Artifact location: /opt/***/mlflow_artifacts
[2025-06-19T11:21:07.066+0000] {logging_mixin.py:188} INFO - Artifact location exists: True
[2025-06-19T11:21:07.066+0000] {logging_mixin.py:188} INFO - Artifact location permissions: 777
[2025-06-19T11:21:07.090+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T11:21:07.141+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:21:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T11:21:07.177+0000] {logging_mixin.py:188} INFO - Started MLflow run: evaluation_run
[2025-06-19T11:21:07.178+0000] {logging_mixin.py:188} INFO - Run ID: c3bffd69a0e8485dbc7e395c3d4c1540
[2025-06-19T11:21:07.192+0000] {logging_mixin.py:188} INFO - Run artifact URI: /mlflow/artifacts/1/c3bffd69a0e8485dbc7e395c3d4c1540/artifacts
[2025-06-19T11:21:07.208+0000] {logging_mixin.py:188} INFO - Starting model evaluation process...
[2025-06-19T11:21:07.221+0000] {logging_mixin.py:188} INFO - Evaluating regression model...
[2025-06-19T11:21:08.008+0000] {logging_mixin.py:188} INFO - Model evaluation completed:
[2025-06-19T11:21:08.009+0000] {logging_mixin.py:188} INFO - - mean_squared_error: 0.0297
[2025-06-19T11:21:08.009+0000] {logging_mixin.py:188} INFO - - root_mean_squared_error: 0.1722
[2025-06-19T11:21:08.009+0000] {logging_mixin.py:188} INFO - - mean_absolute_error: 0.0547
[2025-06-19T11:21:08.009+0000] {logging_mixin.py:188} INFO - - r2_score: 0.9991
[2025-06-19T11:21:08.010+0000] {logging_mixin.py:188} INFO - Error in log_metrics: float() argument must be a string or a number, not 'dict'
[2025-06-19T11:21:08.023+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:21:08 INFO mlflow.tracking._tracking_service.client: üèÉ View run evaluation_run at: http://mlflow:5000/#/experiments/1/runs/c3bffd69a0e8485dbc7e395c3d4c1540.
[2025-06-19T11:21:08.024+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:21:08 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-19T11:21:08.035+0000] {logging_mixin.py:188} INFO - Ended MLflow run
[2025-06-19T11:21:08.092+0000] {python.py:202} INFO - Done. Returned value was: Model evaluation completed
[2025-06-19T11:21:08.136+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=lung_cancer_ml_pipeline, task_id=evaluate_model_task, execution_date=20250619T111539, start_date=20250619T112106, end_date=20250619T112108
[2025-06-19T11:21:08.206+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:21:08.224+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
